name: Sync and Run Scripts

on:
  push:
    branches: [ main ]

jobs:
  sync-and-run:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run script
      run: |
        # Stop any existing instance
        sudo pm2 stop your-script || true
        # Start new instance
        sudo pm2 start your-script.js
        # Save PM2 configuration
        sudo pm2 save