name: Sync and Run Scripts

on:
  push:
    branches: [ main ]

jobs:
  sync-and-run:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
      with:
        arduino-cli-version: '0.19.0'

    - name: Update Arduino CLI
      run: arduino-cli core update-index
      


    - name: Install Arduino core
      run: arduino-cli core install arduino:avr

    - name: compile code for Arduino
      run: arduino-cli compile --fqbn arduino:avr:uno ./ArduinoController
      
    - name: Upload the code to the Arduino
      run: arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:uno ./ArduinoController
      
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'
        
    - name: Install dependencies
      run: npm install

    
    - name: Run script
      run: |
        ./scripts/startup/start.sh